### ISSUE TITLE
Error: Library tink_macro version 0.0.0-beta is not installed

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [haxetink/tink_lang#1]
Hey,

Trying to use tink_lang. It requires tink_macro. I tried to install it via haxelib install tink_macro and haxelib git. But I always get the error:

```
Error: Library tink_macro version 0.0.0-beta is not installed
```

I am on linux mint 64 bit using haxe 3.1.0.

**Comment by back2dos** [comment]
I'm afraid tink_lang is not ready for use just yet. Some of the
documentation is not actually even implemented yet.
I plan to finish and release it shortly after Haxe 3.1.0 which seems to be
scheduled for mid February.

**Comment by retorquere** [comment]
Does "not ready for use just yet" still apply?

**Comment by back2dos** [comment]
Not really. However I do have a couple of breaking changes coming before
the final release:
1. `implements tink.Lang` will be replaced with `@:tink` metadata (although
   I plan to have a deprecation period for the former).
2. `@do body` notation will require the body to be a block to avoid
   confusion.

But I myself am currently using this library in a handful of projects, so
in my own interest I will keep any changes manageable ;)

**Comment by back2dos** [comment]
Now available through haxelib.
