### ISSUE TITLE
Implicit return on functions defined by an interface

### ISSUE THREAD

**Issue by fullofcaffeine** [haxetink/tink_lang#13]
Given an interface:

```
interface IFoo {
  public function fooberize(arg:String):Int;
}
```

And a class implementing IFoo:

```
class Bar implements IFoo {

  public function fooberize(arg:String):Int {
    1337; //Is it possible to return implicitly here, like this? Right now, Haxe won't allow me to compile
  }   
}
```

As per the comments above, is it possible to do it like so?

**Comment by back2dos** [comment]
Possible, yes. But I'm really not sure it's worth it, as it would take quite a bit of heavy lifting only to save you one keyword per function.

**Comment by fullofcaffeine** [comment]
I tried adding `@:tink` to the interface itself (not sure if it makes sense, I'm pretty much trialing and error'ing now, since I'm just beginning with it), and it fails with:

```
haxe build.hxml                                                                                                           [2.2.1]
/usr/lib/haxe/lib/tink_lang/0,3,0/src/tink/lang/sugar/ComplexDefaultArguments.hx:31: characters 13-24 : Invalid field access : expr
/usr/lib/haxe/lib/tink_lang/0,3,0/src/tink/lang/sugar/ComplexDefaultArguments.hx:12: characters 25-42 : Called from
/usr/lib/haxe/lib/tink_lang/0,3,0/src/tink/lang/Sugar.hx:230: characters 64-68 : Called from
/usr/lib/haxe/lib/tink_syntaxhub/0,3,3/src/tink/SyntaxHub.hx:43: characters 16-31 : Called from
?:1: characters 2-7 : Called from
Aborted
```

**Comment by fullofcaffeine** [comment]
@back2dos Cool. I was just curious, really. It's not something that worries me too much, even though it'd be nice to keep some of my Ruby habits, I'm fine writing `return` ;)

**Comment by back2dos** [comment]
The above error was a bug. Adding `@:tink` to an interface [does have a meaning](https://github.com/haxetink/tink_lang#partial-implementation), altbeit not the one you're after.

**Comment by fullofcaffeine** [comment]
Thanks.
