### ISSUE TITLE
@:calculated can't access local class variable.

### ISSUE THREAD

**Issue by 5Mixer** [haxetink/tink_lang#14]
Hi again,
I was using @:calculated to return a different sprite depending one whether this particular object was full, and came into an issue.

public var isFilled:Bool = false;
@:calculated public var spriteID:Int = if (isFilled) 5 else 6;

For now I am just going to make it a function and pass it in as a getter, but I thought it was worth bringing up, as often the data in your expression will use local class variables.
Edit sorry this was a crap issue description, here is the error, although I presume you already know what I am talking about lol. The error is "Cannot access this or other member field in variable initialization"

**Comment by back2dos** [comment]
The error you've mentioned indicates that your class lacks the `@:tink` metadata ;)

**Comment by 5Mixer** [comment]
You were right (I hadn't added tinkling to the project either, only tink_core). My completely unrelated issue though is that I can't put (get,set) there, and neither can tink, because the interface I declared it in didn't have that for the variable.

That's completely unrelated to tink though so don't worry about it. Thanks again for helping me with tink :)
