### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by as3boyan** [haxetink/tink_lang#2]
as3boyan@as3boyan ~/haxetink/tink_lang $ haxe tests.hxml
src/tink/Lang.hx:4: characters 3-12 : The macro didn't return a valid result
as3boyan@as3boyan ~/haxetink/tink_lang $ haxe tink_lang.hxml 
src/tink/Lang.hx:4: characters 3-12 : The macro didn't return a valid result

Haxe 3.1.3

**Comment by back2dos** [comment]
Should work now.
