### ISSUE TITLE
@:calc does not work on static var

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_lang#21]
The getter is generated [here](https://github.com/haxetink/tink_lang/blob/e922cb4/src/tink/lang/sugar/PropertyNotation.hx#L100) which in turns call [Member.getter](https://github.com/haxetink/tink_macro/blob/c0b562a/src/tink/macro/Member.hx#L17). But none of them has ever cared if the member is static or not.

**Comment by back2dos** [comment]
Oh, that use case never really occurred to me. I suspect much of the other things also don't work on static fields.
