### ISSUE TITLE
Key-value loops for anonymous structures

### ISSUE THREAD

**Issue by retorquere** [haxetink/tink_lang#3]
Would it be possible to add support for key-value loops over anonymous structures? Instead of accessing keys() you could get fields()

**Comment by back2dos** [comment]
Tink embraces the use of type safe code, so generally I'm not very inclined to allow this arbitrarily for anonymous structures - even setting aside the fact that such a structure could always have a `keys` and a `get` method in which case it's unclear which kind of iteration to go for. 

However, the standard lib has recently added support for accessing anonymous structures much like maps in a type safe way: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/DynamicAccess.hx

If you use that, then you will get key-value loops for free. Would that work for you?

**Comment by retorquere** [comment]
Yes, it would. This lib would be released with the next Haxe version?

**Comment by back2dos** [comment]
Yep, exactly. I was hoping for Haxe 3.2.0 shortly after the WWX in May, but
I'm still waiting. It looks as though the guys are getting close though ;)
