### ISSUE TITLE
Support for optional arguments in arrow lambdas

### ISSUE THREAD

**Issue by serjek** [haxetink/tink_lang#31]
Noticed that arrow lambda does not support optional arguments as this
`{[a,?b] => Promise.NOISE;}` returns error `Expected expression`

Would be nice to have them parsed to keep user's code consistent.

**Comment by back2dos** [comment]
That's not going to parse, I'm afraid. We could support `[a, @:optional b] => Promise.NOISE`. At that point, it's probably easier to just use normal function syntax though.

If you're on Haxe 4, you can just use standard syntax `(a, ?b) -> Promise.NOISE` though ;)
