### ISSUE TITLE
Type not found : Callback

### ISSUE THREAD

**Issue by ricochet1k** [haxetink/tink_lang#37]
```
/home/matt/haxe/haxe_libraries/tink_lang/0.6.0/haxelib/src/tink/lang/Sugar.hx:16: characters 18-40 : Type not found : Callback
```
When I fix that by changing to `tink.core.Callback`, I get this error:
```
/home/matt/haxe/haxe_libraries/tink_lang/0.6.0/haxelib/src/tink/lang/Sugar.hx:74: characters 17-19 : Unexpected in
```

I've tried this with every version from 0.6.0 to 0.6.3

I encounter these in my editor's language server, and also when trying to build documentation:
```
--library tink_http
--library tink_cli
--library tink_lang
--library yaml
-D no-deprecation-warnings
--class-path cli

--neko screepscli.n
-D doc-gen
--xml doc/cli.xml
--macro include('tink')
--macro include('yaml')
--no-output

--next 

--cmd haxelib run dox -i doc/cli.xml -o doc/cli/
```

**Comment by back2dos** [comment]
Using `--macro include('tink')` is not supported. It tries to include a whole lot of macro code into the output (that's the error you're currently seeing). This is very similar to `haxe --macro include('haxe')`, which runs into the same kind of error.

Please note that `include` also messes with typing order. Use it with caution, even on your own code. You should find a more selective approach. From what I see there, this should have the intended effect:

```
--library tink_http
--library tink_cli
--library tink_lang
--library yaml
-D no-deprecation-warnings
--class-path cli

--neko screepscli.n
-D doc-gen
--xml doc/cli.xml
tink.http.Client
tink.http.Container
yaml.Yaml
--no-output

--next 

--cmd haxelib run dox -i doc/cli.xml -o doc/cli/
```

Perhaps using the normal application entry point will be just as adequate and also more future proof though ;)

**Comment by ricochet1k** [comment]
Okay, that's nice to know, and it fixes *that* problem, but I also get those errors with the following:
```
--library tink_lang
--class-path src
--class-path ts/externs/typed-screeps
--dce full
-D analyzer-optimize
-D js-es=6
--js screeps.js
--main Main
```
I'm using lix, if that makes any difference.

**Comment by back2dos** [comment]
The something in your code would seem to import tink.macro.Sugar into regular context. Can you please provide a minimal example?

**Comment by ricochet1k** [comment]
Just kidding. Looks like I screwed up my ~/haxe_libraries folder. I deleted them all and did `lix download` again and everything looks fine now.
